    // ---------- 样式（主题变量 + 兜底色） ----------
    const S = {
      trigger: (wide) => ({
        display: "flex",
        alignItems: "center",
        gap: 6,
        padding: wide ? "6px 10px" : "6px",
        margin: "0 6px 6px",
        borderRadius: 8,
        border: "1px solid transparent",
        background: "transparent",
        color: "var(--dsw-alias-label-secondary, #9a9aa0)",
        fontSize: 12,
        lineHeight: 1.4,
        cursor: "pointer",
        whiteSpace: "nowrap",
        textAlign: "left",
        width: wide ? "auto" : 32,
        justifyContent: wide ? "flex-start" : "center",
      }),
      overlay: { position: "fixed", inset: 0, zIndex: 9999 },
      backdrop: { position: "absolute", inset: 0, background: "rgba(0,0,0,0.35)" },
      panel: {
        position: "absolute",
        top: 0,
        right: 0,
        bottom: 0,
        width: 400,
        maxWidth: "94vw",
        background: "var(--dsw-alias-bg-layer-2, #202024)",
        color: "var(--dsw-alias-label-primary, #ececf0)",
        boxShadow: "-10px 0 32px rgba(0,0,0,0.4)",
        display: "flex",
        flexDirection: "column",
        fontFamily: "system-ui, -apple-system, 'Segoe UI', 'PingFang SC', 'Microsoft YaHei', sans-serif",
        fontSize: 13,
      },
      header: {
        padding: "14px 16px 10px",
        borderBottom: "1px solid var(--dsw-alias-interactive-bg-hover, #333338)",
        display: "flex",
        alignItems: "flex-start",
        justifyContent: "space-between",
        gap: 8,
      },
      title: { margin: 0, fontSize: 15, fontWeight: 600 },
      subtitle: { margin: "3px 0 0", fontSize: 12, color: "var(--dsw-alias-label-secondary, #9a9aa0)" },
      close: {
        background: "transparent",
        border: "none",
        color: "var(--dsw-alias-label-secondary, #9a9aa0)",
        fontSize: 16,
        lineHeight: 1,
        cursor: "pointer",
        padding: "2px 6px",
        borderRadius: 6,
      },
      tabs: { display: "flex", gap: 4, padding: "8px 12px 0", borderBottom: "1px solid var(--dsw-alias-interactive-bg-hover, #333338)" },
      tab: (active) => ({
        background: active ? "var(--dsw-alias-interactive-bg-hover, #333338)" : "transparent",
        border: "none",
        color: active ? "var(--dsw-alias-label-primary, #ececf0)" : "var(--dsw-alias-label-secondary, #9a9aa0)",
        padding: "6px 12px",
        borderRadius: "8px 8px 0 0",
        fontSize: 12.5,
        cursor: "pointer",
      }),
      body: { flex: 1, overflowY: "auto", padding: "8px 12px 16px" },
      row: {
        // v1.37.0：会话行改为纵向卡片——顶部状态（checkbox+徽章）/ 中间内容 / 下方操作集中
        display: "flex",
        flexDirection: "column",
        alignItems: "stretch",
        gap: 7,
        padding: "8px 10px",
        borderRadius: 8,
        border: "1px solid var(--dsw-alias-interactive-bg-hover, #2e2e33)",
        marginTop: 6,
        cursor: "pointer",
      },
      // 顶部状态行：批量勾选 + 状态徽章
      rowTop: {
        display: "flex",
        alignItems: "center",
        gap: 6,
        flexShrink: 0,
        minHeight: 20,
      },
      rowTopBadges: {
        display: "flex",
        alignItems: "center",
        gap: 5,
        flexShrink: 0,
        marginLeft: "auto",
      },
      groupHeader: {
        display: "flex",
        alignItems: "center",
        gap: 6,
        padding: "8px 10px 4px",
        marginTop: 10,
        cursor: "pointer",
        userSelect: "none",
        borderBottom: "1px solid var(--dsw-alias-interactive-bg-hover, #2e2e33)",
      },
      groupCaret: { fontSize: 10, color: "var(--dsw-alias-label-secondary, #9a9aa0)", flexShrink: 0 },
      groupTitle: { fontWeight: 700, fontSize: 12.5, flex: 1, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
      groupCount: {
        flexShrink: 0,
        fontSize: 10.5,
        padding: "1px 8px",
        borderRadius: 999,
        border: "1px solid var(--dsw-alias-interactive-bg-hover, #3a3a40)",
        color: "var(--dsw-alias-label-secondary, #9a9aa0)",
      },
      groupList: { paddingLeft: 2 },
      rowMain: { flex: 1, minWidth: 0 },
      rowTitle: {
        display: "flex",
        alignItems: "flex-start", // v1.25.0：标题最多 3 行时徽章顶部对齐不被挤压
        gap: 6,
        fontWeight: 600,
        fontSize: 13,
        overflow: "hidden",
        lineHeight: 1.35,
      },
      rowMeta: { marginTop: 2, fontSize: 11.5, color: "var(--dsw-alias-label-secondary, #9a9aa0)", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
      // v1.25.0：第三行小字 session id（等宽小字号，方便复制/排查）
      rowSid: { marginTop: 2, fontSize: 10.5, fontFamily: "ui-monospace,SFMono-Regular,Menlo,Consolas,monospace", color: "var(--dsw-alias-label-tertiary, #6f6f76)", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", userSelect: "text" },
      badge: (kind) => ({
        flexShrink: 0,
        fontSize: 10.5,
        padding: "1px 7px",
        borderRadius: 999,
        border: "1px solid",
        ...(kind === "archived"
          ? { color: "var(--dsw-alias-label-secondary, #9a9aa0)", borderColor: "#55555c" }
          : kind === "running"
            ? { color: "var(--dsw-state-success-primary, #4caf7d)", borderColor: "currentColor" }
            : { color: "var(--dsw-alias-label-tertiary, #77777d)", borderColor: "currentColor" }),
      }),
      actions: { flexShrink: 0, display: "flex", gap: 6, justifyContent: "flex-end", flexWrap: "wrap" },
      actionsCol: { flexShrink: 0, display: "flex", flexDirection: "column", alignItems: "flex-end", gap: 5 },
      // v1.37.0：下方操作集中区（开关行 + 按钮行，纵向堆叠）
      rowOps: { display: "flex", flexDirection: "column", gap: 6, flexShrink: 0 },
      opsToggles: { display: "flex", alignItems: "center", gap: 14 },
      opsButtons: { display: "flex", gap: 6, flexWrap: "wrap", justifyContent: "flex-start" },
      autoToggle: {
        display: "flex",
        alignItems: "center",
        gap: 4,
        fontSize: 11,
        color: "var(--dsw-alias-label-secondary, #9a9aa0)",
        cursor: "pointer",
        userSelect: "none",
        whiteSpace: "nowrap",
      },
      actionBtn: (danger) => ({
        background: "transparent",
        border: danger ? "1px solid var(--dsw-state-error-primary, #d9534f)" : "1px solid var(--dsw-alias-interactive-bg-hover, #3a3a40)",
        color: danger ? "var(--dsw-state-error-primary, #d9534f)" : "var(--dsw-alias-label-secondary, #d0d0d6)",
        borderRadius: 6,
        padding: "3px 9px",
        fontSize: 11.5,
        cursor: "pointer",
      }),
      hint: { margin: "10px 0 6px", fontSize: 12, color: "var(--dsw-alias-label-secondary, #9a9aa0)" },
      helpBlock: {
        marginTop: 10,
        padding: "10px 12px",
        borderRadius: 8,
        background: "var(--dsw-alias-interactive-bg-hover, #2a2a30)",
        border: "1px solid var(--dsw-alias-interactive-bg-hover, #333338)",
      },
      helpTitle: { fontWeight: 600, fontSize: 13, margin: "0 0 4px" },
      helpDesc: { margin: 0, fontSize: 12.5, lineHeight: 1.65, color: "var(--dsw-alias-label-secondary, #c8c8ce)" },
      empty: { marginTop: 24, textAlign: "center", color: "var(--dsw-alias-label-tertiary, #77777d)", fontSize: 12.5 },
      error: { marginTop: 10, padding: "8px 10px", borderRadius: 8, border: "1px solid var(--dsw-state-error-primary, #d9534f)", color: "var(--dsw-state-error-primary, #d9534f)", fontSize: 12 },
    };

    // ---------- 组件 ----------

    // 会话列表长效缓存（localStorage）：插件启动即预取 + 每次刷新落盘，面板重开/页面刷新秒显历史数据
